# General site settings
title: Cedric Helewaut
email: cedrichelewaut18@gmail.com
description: Ghent-based Computer Engineer
author: Cedric Helewaut
baseurl: ""
url: ""

# Social profiles
github_username: cedrichelewaut
linkedin_username: cedrichelewaut
instagram_username: cedrichelewaut

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
